site_name: OVOS User Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Home:
        - Introduction: index.md
        - About: about.md
        - Supported Hardware: hardware.md
            - Audio: hardware_audio.md
            - Video: hardware_video.md
        - OpenVoiceOS Architecture: architecture.md
    - Quick Start Guide:
        - Introduction: qs_intro.md
        - First Boot: qs_first_boot.md
        - Next Steps: qs_next_steps.md
    - Installation Options:
        - Introduction: install_intro.md
        - Installing an Image: qs_intro.md
        - Install as a Library: install_ovos_core.md
        - Install with Docker: install_ovos_docker.md
        - Install GUI: install_gui.md
    - Starting OVOS:
        - Introduction: starting_intro.md
        - Starting Modules: starting_modules.md
        - Starting Systemd: starting_systemd.md
        - Starting Docker: starting_docker.md
    - Configuration:
        - Introduction: config.md
        - Using ovos-config: config_ovos_config.md
        - Manualy Editing Files: config_manual_config.md
    - How To:
        - Introduction: ht_intro.md
        - Skills: ht_skills.md
            - Installing Skills: ht_skills_install.md
            - Configuring: ht_skills_config.md
        - TTS: ht_tts.md
            - Configuring: ht_tts_config.md
            - Change Your Assistant's Voice: ht_change_voice.md
        - Listener: ht_listener_intro.md
            - Microphone: ht_mic.md
            - STT: ht_stt.md
            - WakeWord/HotWords: ht_ww.md
            - VAD: ht_vad.md
        - PHAL: ht_phal.md
        - Homescreen:
            - Configuration: ht_config_homescreen.md
        - OpenVoiceOS Security: ht_config_security.md
    - Additional Services:
        - Selene Backend: selene_backend.md
        - Personal Backend: personal_backend.md
        - KDE Connect: kdeconnect.md
    - Images:
        - Introduction: images_intro.md
        - Buildroot: images_buildroot.md
        - Raspbian: install_raspbian.md
    - Other Builds:
        - Mycroft: mycroft.md
        - NeonOS: neonos.md
    - Troubleshooting:
          - Introduction to Troubleshooting: troubleshooting_intro.md
          - Troubleshooting Audio: troubleshooting_audio.md
          - Troubleshooting Installation: troubleshooting_installation.md
          - Troubleshooting Network: troubleshooting_network.md
          - Troubleshooting Wakeword: troubleshooting_wakeword.md
          - Troubleshooting OVOS Core: troubleshooting_ovos_core.md
          - Troubleshooting Backend: troubleshooting_backend.md
          - Troubleshooting TTS: troubleshooting_tts.md
          - Troubleshooting STT: troubleshooting_stt.md
          - Troubleshooting Skills: troubleshooting_skills.md
          - Troubleshooting Plugins: troubleshooting_plugins.md
    - Appendix:
        - Glossary: glossary.md
        - FAQ: faq.md
        - Compatibility: compat.md
        - License: license.md
        - Friends: friends.md
        - OVOS Members: members.md
theme: readthedocs
