site_name: Documentation
site_url: https://openvoiceos.github.io/community-docs
nav:
    - Home:
        - Introduction: index.md
        - Glossary: glossary.md
        - Getting Started: setup_getting_started.md
        - License: license.md
    - Overview:
        - F.A.Q.: faq.md
        - Backend Services: backend.md
        - Configuration: config.md
        - Friends: friends.md
    - OVOS-core:
        - Introduction: core.md
        - Bus: bus_service.md
        - Skills: skills_service.md
        - Speech: speech_service.md
        - Audio: audio_service.md
        - GUI: gui_service.md
    - Skills:
        - Introduction: skills.md
        - Design Guidelines: guidelines.md
        - Anatomy: skill_structure.md
        - Dialog: statements.md
        - Prompts: prompts.md
        - Intents: intents.md
        - Context: context.md
        - Converse: converse.md
        - Filesystem: skill_filesystem.md
        - Skill Settings: skill_settings.md
        - Skill GUI: skill_gui.md
        - Skill API: skill_api.md
        - F.A.Q.: dev.md
    - Technologies:
        - Skills Manager: osm.md
        - Platform/Hardware Abstraction Layer: PHAL.md
        - Plugin Manager: OPM.md
        - Personal Backend: personal_backend.md
        - Shell: shell.md
        - Common Play: OCP.md
        - Config Assistant: OCA.md
        - Open Linguistika: linguistika.md
        - STT Server: stt_server.md
        - TTS Server: tts_server.md
        - Translate Server: translate_server.md
    - Images:
        - Buildroot: buildroot.md
        - Manjaro: manjaro.md
    - Mycroft:
        - Compatibility: compat.md
        - Comparison: mycroft.md

theme: readthedocs
